# Generated by Django 5.1.8 on 2025-06-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0709_navigationview"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="allow_external_message_editing",
            field=models.BooleanField(default=True),
        ),
    ]
