# Generated by Django 5.1.8 on 2025-06-06 11:03

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0710_realm_allow_external_message_editing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedusermessage",
            name="flags",
            field=bitfield.models.BitField(
                [
                    "read",
                    "starred",
                    "collapsed",
                    "mentioned",
                    "stream_wildcard_mentioned",
                    "topic_wildcard_mentioned",
                    "group_mentioned",
                    "force_expand",
                    "force_collapse",
                    "has_alert_word",
                    "historical",
                    "is_private",
                    "active_mobile_push_notification",
                    "editable_by_others",
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="flags",
            field=bitfield.models.BitField(
                [
                    "read",
                    "starred",
                    "collapsed",
                    "mentioned",
                    "stream_wildcard_mentioned",
                    "topic_wildcard_mentioned",
                    "group_mentioned",
                    "force_expand",
                    "force_collapse",
                    "has_alert_word",
                    "historical",
                    "is_private",
                    "active_mobile_push_notification",
                    "editable_by_others",
                ],
                default=0,
            ),
        ),
    ]
