# Generated by Django 5.2.3 on 2025-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0718_fix_topics_for_direct_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="only_general_chat_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
