# Generated by Django 5.2.3 on 2025-06-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0719_realm_only_general_chat_allowed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="only_general_chat_allowed",
        ),
    ]
